// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type GoalsCategoryType string

const (
	GoalsCategoryTypeGrowth      GoalsCategoryType = "growth"
	GoalsCategoryTypeMaintenance GoalsCategoryType = "maintenance"
	GoalsCategoryTypeOther       GoalsCategoryType = "other"
)

func (e *GoalsCategoryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GoalsCategoryType(s)
	case string:
		*e = GoalsCategoryType(s)
	default:
		return fmt.Errorf("unsupported scan type for GoalsCategoryType: %T", src)
	}
	return nil
}

type NullGoalsCategoryType struct {
	GoalsCategoryType GoalsCategoryType `json:"goals_category_type"`
	Valid             bool              `json:"valid"` // Valid is true if GoalsCategoryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGoalsCategoryType) Scan(value interface{}) error {
	if value == nil {
		ns.GoalsCategoryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GoalsCategoryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGoalsCategoryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GoalsCategoryType), nil
}

type Goal struct {
	ID           int64             `json:"id"`
	UserID       int32             `json:"user_id"`
	Title        string            `json:"title"`
	Color        pgtype.Text       `json:"color"`
	CategoryType GoalsCategoryType `json:"category_type"`
	IsArchived   bool              `json:"is_archived"`
	CreatedAt    pgtype.Timestamp  `json:"created_at"`
}

type RecurringTasksTemplate struct {
	ID                int64            `json:"id"`
	UserID            int32            `json:"user_id"`
	GoalID            int32            `json:"goal_id"`
	Title             string           `json:"title"`
	DurationMinutes   int32            `json:"duration_minutes"`
	RecurrenceRrule   string           `json:"recurrence_rrule"`
	LastGeneratedDate pgtype.Date      `json:"last_generated_date"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type Task struct {
	ID              int64            `json:"id"`
	UserID          int32            `json:"user_id"`
	GoalID          int32            `json:"goal_id"`
	Title           string           `json:"title"`
	IsDone          bool             `json:"is_done"`
	ScheduledDate   pgtype.Date      `json:"scheduled_date"`
	ScheduledTime   pgtype.Time      `json:"scheduled_time"`
	DurationMinutes pgtype.Int4      `json:"duration_minutes"`
	RescheduleCount int32            `json:"reschedule_count"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID           int64            `json:"id"`
	Email        string           `json:"email"`
	PasswordHash pgtype.Text      `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}
