// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteGoalByID(ctx context.Context, arg DeleteGoalByIDParams) error
	GetGoalByID(ctx context.Context, arg GetGoalByIDParams) (Goal, error)
	GetUser(ctx context.Context, email string) (User, error)
	ListGoals(ctx context.Context, userID int32) ([]Goal, error)
	ListGoalsByIsArchived(ctx context.Context, arg ListGoalsByIsArchivedParams) ([]Goal, error)
	UpdateGoalByID(ctx context.Context, arg UpdateGoalByIDParams) error
}

var _ Querier = (*Queries)(nil)
