// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recurring_tasks_templates.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecurringTasksTemplate = `-- name: CreateRecurringTasksTemplate :one
INSERT INTO recurring_tasks_templates (
    user_id, goal_id, title, scheduled_datetime, has_time, duration_minutes, recurrence_rrule
) VALUES (
             $1, $2, $3, $4, $5, $6, $7
         )
    RETURNING id, user_id, goal_id, title, scheduled_datetime, has_time, duration_minutes, recurrence_rrule, last_generated_date, created_at
`

type CreateRecurringTasksTemplateParams struct {
	UserID            int32            `json:"user_id"`
	GoalID            int32            `json:"goal_id"`
	Title             string           `json:"title"`
	ScheduledDatetime pgtype.Timestamp `json:"scheduled_datetime"`
	HasTime           bool             `json:"has_time"`
	DurationMinutes   int32            `json:"duration_minutes"`
	RecurrenceRrule   string           `json:"recurrence_rrule"`
}

func (q *Queries) CreateRecurringTasksTemplate(ctx context.Context, arg CreateRecurringTasksTemplateParams) (RecurringTasksTemplate, error) {
	row := q.db.QueryRow(ctx, createRecurringTasksTemplate,
		arg.UserID,
		arg.GoalID,
		arg.Title,
		arg.ScheduledDatetime,
		arg.HasTime,
		arg.DurationMinutes,
		arg.RecurrenceRrule,
	)
	var i RecurringTasksTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoalID,
		&i.Title,
		&i.ScheduledDatetime,
		&i.HasTime,
		&i.DurationMinutes,
		&i.RecurrenceRrule,
		&i.LastGeneratedDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRecurringTasksTemplateByID = `-- name: DeleteRecurringTasksTemplateByID :exec
DELETE FROM recurring_tasks_templates
WHERE id = $1 AND user_id = $2
`

type DeleteRecurringTasksTemplateByIDParams struct {
	ID     int64 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteRecurringTasksTemplateByID(ctx context.Context, arg DeleteRecurringTasksTemplateByIDParams) error {
	_, err := q.db.Exec(ctx, deleteRecurringTasksTemplateByID, arg.ID, arg.UserID)
	return err
}

const getRecurringTasksTemplateByID = `-- name: GetRecurringTasksTemplateByID :one
SELECT id, user_id, goal_id, title, scheduled_datetime, has_time, duration_minutes, recurrence_rrule, last_generated_date, created_at FROM recurring_tasks_templates
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetRecurringTasksTemplateByIDParams struct {
	ID     int64 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetRecurringTasksTemplateByID(ctx context.Context, arg GetRecurringTasksTemplateByIDParams) (RecurringTasksTemplate, error) {
	row := q.db.QueryRow(ctx, getRecurringTasksTemplateByID, arg.ID, arg.UserID)
	var i RecurringTasksTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoalID,
		&i.Title,
		&i.ScheduledDatetime,
		&i.HasTime,
		&i.DurationMinutes,
		&i.RecurrenceRrule,
		&i.LastGeneratedDate,
		&i.CreatedAt,
	)
	return i, err
}

const listRecurringTasksTemplates = `-- name: ListRecurringTasksTemplates :many
SELECT id, user_id, goal_id, title, scheduled_datetime, has_time, duration_minutes, recurrence_rrule, last_generated_date, created_at FROM recurring_tasks_templates
WHERE user_id = $1
ORDER BY id
`

func (q *Queries) ListRecurringTasksTemplates(ctx context.Context, userID int32) ([]RecurringTasksTemplate, error) {
	rows, err := q.db.Query(ctx, listRecurringTasksTemplates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringTasksTemplate
	for rows.Next() {
		var i RecurringTasksTemplate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GoalID,
			&i.Title,
			&i.ScheduledDatetime,
			&i.HasTime,
			&i.DurationMinutes,
			&i.RecurrenceRrule,
			&i.LastGeneratedDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringTasksTemplatesDueForGeneration = `-- name: ListRecurringTasksTemplatesDueForGeneration :many
SELECT id, user_id, goal_id, title, scheduled_datetime, has_time, duration_minutes, recurrence_rrule, last_generated_date, created_at FROM recurring_tasks_templates
WHERE last_generated_date < (current_date + interval '1 month')
`

func (q *Queries) ListRecurringTasksTemplatesDueForGeneration(ctx context.Context) ([]RecurringTasksTemplate, error) {
	rows, err := q.db.Query(ctx, listRecurringTasksTemplatesDueForGeneration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringTasksTemplate
	for rows.Next() {
		var i RecurringTasksTemplate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GoalID,
			&i.Title,
			&i.ScheduledDatetime,
			&i.HasTime,
			&i.DurationMinutes,
			&i.RecurrenceRrule,
			&i.LastGeneratedDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastGeneratedDateInRecurringTasksTemplateByID = `-- name: UpdateLastGeneratedDateInRecurringTasksTemplateByID :exec
UPDATE recurring_tasks_templates
SET last_generated_date = $2
WHERE id = $1
`

type UpdateLastGeneratedDateInRecurringTasksTemplateByIDParams struct {
	ID                int64       `json:"id"`
	LastGeneratedDate pgtype.Date `json:"last_generated_date"`
}

func (q *Queries) UpdateLastGeneratedDateInRecurringTasksTemplateByID(ctx context.Context, arg UpdateLastGeneratedDateInRecurringTasksTemplateByIDParams) error {
	_, err := q.db.Exec(ctx, updateLastGeneratedDateInRecurringTasksTemplateByID, arg.ID, arg.LastGeneratedDate)
	return err
}

const updateRecurringTasksTemplateByID = `-- name: UpdateRecurringTasksTemplateByID :exec
UPDATE recurring_tasks_templates
SET
    goal_id = $3,
    title = $4,
    scheduled_datetime = $5,
    has_time = $6,
    duration_minutes = $7,
    recurrence_rrule = $8
WHERE id = $1 AND user_id = $2
`

type UpdateRecurringTasksTemplateByIDParams struct {
	ID                int64            `json:"id"`
	UserID            int32            `json:"user_id"`
	GoalID            int32            `json:"goal_id"`
	Title             string           `json:"title"`
	ScheduledDatetime pgtype.Timestamp `json:"scheduled_datetime"`
	HasTime           bool             `json:"has_time"`
	DurationMinutes   int32            `json:"duration_minutes"`
	RecurrenceRrule   string           `json:"recurrence_rrule"`
}

func (q *Queries) UpdateRecurringTasksTemplateByID(ctx context.Context, arg UpdateRecurringTasksTemplateByIDParams) error {
	_, err := q.db.Exec(ctx, updateRecurringTasksTemplateByID,
		arg.ID,
		arg.UserID,
		arg.GoalID,
		arg.Title,
		arg.ScheduledDatetime,
		arg.HasTime,
		arg.DurationMinutes,
		arg.RecurrenceRrule,
	)
	return err
}
